# Lipidomics

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Prepare dataset for LipidSig

In [97]:
df = pd.read_csv(
    '/Users/loictalignani/research/project/lipidomics/data/lipidsig/MISSE_Global_Lipidomics_results_all.tsv', sep="\t")
df

,feature,BS-064D0,BS-064D03,BS-064D10,BS-064D60,BS-082D0,BS-082D03,BS-082D10,BS-082D60,BS-336D0,...,KT-880D10,KT-880D60,KT-926D0,KT-926D03,KT-926D10,KT-926D60,KT-974D0,KT-974D03,KT-974D10,KT-974D60
0,DG 30:0,"0,00","0,00","0,00","0,00","0,00","0,00","0,00","0,00","0,00",...,"0,00","0,00","0,00","0,00","0,00","0,00","0,00","0,00","0,00","0,00"
1,DG 32:0,"0,75","0,78","1,41","0,95","0,53","0,00","0,86","0,51","0,00",...,"1,91","2,56","1,15","0,91","0,90","0,39","0,00","0,41","0,00","0,48"
2,DG 32:1,"0,00","0,86","1,73","0,00","0,37","0,00","0,76","0,48","0,00",...,"1,67","0,00","1,15","0,37","0,00","0,00","0,00","0,00","0,00","0,00"
3,DG 34:1,"2,27","4,10","5,12","4,79","2,40","1,97","3,17","1,78","1,68",...,"9,87","5,65","8,03","2,95","4,08","1,75","0,88","2,15","1,96","2,57"
4,DG 34:3,"0,00","0,00","0,00","0,00","0,00","0,00","0,00","0,00","0,00",...,"0,00","0,00","0,69","0,00","0,00","0,00","0,00","0,00","0,00","0,00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,PI 34:2,"0,00","0,00","0,00","0,00","0,00","0,00","0,00","0,00","0,00",...,"4,92","3,27","0,00","0,00","0,00","0,00","0,00","0,00","0,00","0,00"
160,PI 36:2,"0,00","3,57","4,47","4,32","0,00","0,00","0,00","0,00","0,00",...,"9,08","9,59","2,20","0,00","0,00","0,00","0,00","0,00","0,00","0,00"
161,PI 36:4,"0,00","4,34","9,45","0,00","0,00","0,00","0,00","0,00","0,00",...,"19,71","6,25","3,63","0,00","0,00","0,00","0,00","0,00","0,00","0,00"
162,PI 38:3,"0,00","0,61","8,18","0,00","0,00","0,00","0,00","0,26","0,00",...,"4,80","7,66","0,52","0,00","0,00","0,00","0,00","0,00","0,52","0,63"
163,PI 38:4,"23,40","31,29","48,70","24,48","5,83","8,92","13,71","22,17","15,85",...,"56,77","15,31","14,42","11,38","25,70","28,14","2,79","17,33","21,42","15,08"

In [99]:
df_D0 = df[["feature"] + df.filter(regex="D0$").columns.tolist()]
column_order = [
    'BS-064', 'JV-035', 'JV-048', 'KT-515', 'KT-926', 'JV-148', 'JV-157',
    'KT-193', 'KT-247', 'KT-312', 'KT-347', 'KT-352', 'KT-417', 'KT-434',
    'KT-522', 'KT-525', 'KT-565', 'KT-612', 'KT-705', 'KT-718', 'JV-071',
    'BS-082', 'BS-336', 'BS-346', 'BS-351', 'BS-364', 'BS-377', 'JV-138',
    'KT-313', 'KT-412', 'KT-445', 'KT-537', 'KT-538', 'KT-539', 'KT-663',
    'KT-695', 'KT-716', 'KT-723', 'KT-771', 'KT-805', 'KT-880', 'KT-974',
    'BS-671'
]
# Ajoute le suffixe D0 à chaque élément de la liste
column_order_d0 = [col + 'D0' for col in column_order]
conditions_column = df_D0.pop('feature')
df_D0 = df_D0.reindex(column_order_d0, axis=1)
if conditions_column is not None:
    df_D0.insert(0, 'feature', conditions_column)
df_D0.fillna(0, inplace=True)
df_D0 = df_D0.replace(',', '.', regex=True)
df_D0

,feature,BS-064D0,JV-035D0,JV-048D0,KT-515D0,KT-926D0,JV-148D0,JV-157D0,KT-193D0,KT-247D0,...,KT-539D0,KT-663D0,KT-695D0,KT-716D0,KT-723D0,KT-771D0,KT-805D0,KT-880D0,KT-974D0,BS-671D0
0,DG 30:0,0.00,0.42,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
1,DG 32:0,0.75,3.28,0.50,0.00,1.15,0.00,0.88,1.65,0.88,...,0.00,0.00,0.00,0.69,0.00,0.85,0.83,0.80,0.00,0.00
2,DG 32:1,0.00,2.45,0.00,0.00,1.15,0.00,0.45,0.90,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.57,0.00,0.00,0.00
3,DG 34:1,2.27,18.08,2.31,0.74,8.03,2.89,3.56,8.93,3.75,...,0.85,0.58,1.25,4.49,0.80,4.02,5.64,4.03,0.88,1.53
4,DG 34:3,0.00,0.57,0.00,0.00,0.69,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,PI 34:2,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
160,PI 36:2,0.00,5.64,2.96,0.00,2.20,3.61,4.07,4.29,3.00,...,0.00,0.00,0.00,0.00,0.00,3.70,4.40,0.00,0.00,0.00
161,PI 36:4,0.00,0.00,0.00,0.00,3.63,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
162,PI 38:3,0.00,6.11,0.00,0.00,0.52,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.21,0.00,0.00,0.00
163,PI 38:4,23.40,9.66,9.18,8.99,14.42,14.52,13.02,23.68,12.62,...,0.00,0.00,3.81,23.73,8.55,15.65,35.05,8.64,2.79,16.15

In [100]:
duplicates = df_D0[df_D0.duplicated(subset=['feature'], keep='first')]
duplicates

Empty DataFrame
Columns: [feature, BS-064D0, JV-035D0, JV-048D0, KT-515D0, KT-926D0, JV-148D0, JV-157D0, KT-193D0, KT-247D0, KT-312D0, KT-347D0, KT-352D0, KT-417D0, KT-434D0, KT-522D0, KT-525D0, KT-565D0, KT-612D0, KT-705D0, KT-718D0, JV-071D0, BS-082D0, BS-336D0, BS-346D0, BS-351D0, BS-364D0, BS-377D0, JV-138D0, KT-313D0, KT-412D0, KT-445D0, KT-537D0, KT-538D0, KT-539D0, KT-663D0, KT-695D0, KT-716D0, KT-723D0, KT-771D0, KT-805D0, KT-880D0, KT-974D0, BS-671D0]
Index: []

[0 rows x 44 columns]

In [101]:
df_D0.to_csv('/Users/loictalignani/research/project/lipidomics/data/lipidsig/Lipid_abundance_data_D0.tsv', sep="\t", index=False)

In [102]:
df_D03 = df[["feature"] + df.filter(regex="D03$").columns.tolist()]
column_order = [
    'BS-064', 'JV-035', 'JV-048', 'KT-515', 'KT-926', 'JV-148', 'JV-157',
    'KT-193', 'KT-247', 'KT-312', 'KT-347', 'KT-352', 'KT-417', 'KT-434',
    'KT-522', 'KT-525', 'KT-565', 'KT-612', 'KT-705', 'KT-718', 'JV-071',
    'BS-082', 'BS-336', 'BS-346', 'BS-351', 'BS-364', 'BS-377', 'JV-138',
    'KT-313', 'KT-412', 'KT-445', 'KT-537', 'KT-538', 'KT-539', 'KT-663',
    'KT-695', 'KT-716', 'KT-723', 'KT-771', 'KT-805', 'KT-880', 'KT-974',
    'BS-671'
]
# Ajoute le suffixe D0 à chaque élément de la liste
column_order_d03 = [col + 'D03' for col in column_order]
conditions_column = df_D03.pop('feature')
df_D03 = df_D03.reindex(column_order_d03, axis=1)
if conditions_column is not None:
    df_D03.insert(0, 'feature', conditions_column)
df_D03.fillna(0, inplace=True)
df_D03 = df_D03.replace(',', '.', regex=True)
df_D03

,feature,BS-064D03,JV-035D03,JV-048D03,KT-515D03,KT-926D03,JV-148D03,JV-157D03,KT-193D03,KT-247D03,...,KT-539D03,KT-663D03,KT-695D03,KT-716D03,KT-723D03,KT-771D03,KT-805D03,KT-880D03,KT-974D03,BS-671D03
0,DG 30:0,0.00,0.00,0.51,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
1,DG 32:0,0.78,0.86,1.04,1.11,0.91,0.97,0.90,2.00,1.21,...,0.00,0.63,0.95,0.56,0.66,0.77,1.10,0.96,0.41,2.09
2,DG 32:1,0.86,1.01,1.20,0.84,0.37,1.80,1.44,0.68,0.00,...,0.00,0.00,0.00,1.32,0.98,0.00,0.00,0.00,0.00,0.88
3,DG 34:1,4.10,4.86,3.96,7.86,2.95,9.14,7.15,9.47,4.84,...,2.11,2.32,2.47,5.91,5.32,7.40,5.46,2.74,2.15,6.12
4,DG 34:3,0.00,0.00,0.00,0.00,0.00,0.84,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.38,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,PI 34:2,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
160,PI 36:2,3.57,5.18,3.66,5.33,0.00,0.00,5.05,3.77,5.29,...,0.00,2.45,3.77,3.47,3.99,5.08,4.89,0.00,0.00,4.32
161,PI 36:4,4.34,5.90,3.55,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
162,PI 38:3,0.61,0.82,0.10,0.64,0.00,0.00,0.00,0.00,0.15,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
163,PI 38:4,31.29,33.79,22.91,22.46,11.38,17.76,24.46,23.56,32.19,...,12.44,10.31,14.92,26.21,17.72,20.96,39.08,4.45,17.33,44.07

In [103]:
df_D03.to_csv(
    '/Users/loictalignani/research/project/lipidomics/data/lipidsig/Lipid_abundance_data_D03.tsv', sep="\t", index=False)

In [104]:
df_D10 = df[["feature"] + df.filter(regex="D10$").columns.tolist()]
column_order = [
    'BS-064', 'JV-035', 'JV-048', 'KT-515', 'KT-926', 'JV-148', 'JV-157',
    'KT-193', 'KT-247', 'KT-312', 'KT-347', 'KT-352', 'KT-417', 'KT-434',
    'KT-522', 'KT-525', 'KT-565', 'KT-612', 'KT-705', 'KT-718', 'JV-071',
    'BS-082', 'BS-336', 'BS-346', 'BS-351', 'BS-364', 'BS-377', 'JV-138',
    'KT-313', 'KT-412', 'KT-445', 'KT-537', 'KT-538', 'KT-539', 'KT-663',
    'KT-695', 'KT-716', 'KT-723', 'KT-771', 'KT-805', 'KT-880', 'KT-974',
    'BS-671'
]
# Ajoute le suffixe D0 à chaque élément de la liste
column_order_d10 = [col + 'D10' for col in column_order]
conditions_column = df_D10.pop('feature')
df_D10 = df_D10.reindex(column_order_d10, axis=1)
if conditions_column is not None:
    df_D10.insert(0, 'feature', conditions_column)
df_D10.fillna(0, inplace=True)
df_D10 = df_D10.replace(',', '.', regex=True)
df_D10

,feature,BS-064D10,JV-035D10,JV-048D10,KT-515D10,KT-926D10,JV-148D10,JV-157D10,KT-193D10,KT-247D10,...,KT-539D10,KT-663D10,KT-695D10,KT-716D10,KT-723D10,KT-771D10,KT-805D10,KT-880D10,KT-974D10,BS-671D10
0,DG 30:0,0.00,1.25,0.00,0.00,0.00,0.58,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.46,0.00,0.00,0.00,0.00
1,DG 32:0,1.41,2.79,0.99,1.80,0.90,1.96,1.10,1.39,1.38,...,0.72,1.85,0.92,0.00,1.40,2.30,2.45,1.91,0.00,0.61
2,DG 32:1,1.73,4.10,0.84,1.67,0.00,2.01,0.80,1.05,1.17,...,0.65,1.89,0.62,0.00,0.95,1.65,2.04,1.67,0.00,0.00
3,DG 34:1,5.12,8.83,4.05,8.30,4.08,6.74,5.50,4.09,7.51,...,4.38,7.58,4.74,1.32,5.43,7.12,10.71,9.87,1.96,3.60
4,DG 34:3,0.00,0.00,0.00,0.43,0.00,0.37,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.44,0.54,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,PI 34:2,0.00,0.00,0.00,2.53,0.00,0.00,0.00,0.00,0.00,...,0.00,3.51,0.00,0.00,0.00,0.00,0.00,4.92,0.00,0.00
160,PI 36:2,4.47,4.76,4.98,5.04,0.00,0.00,4.89,6.20,5.02,...,4.11,7.67,0.00,3.75,2.56,4.45,3.86,9.08,0.00,6.00
161,PI 36:4,9.45,7.03,0.00,7.85,0.00,0.00,4.47,10.60,4.07,...,9.67,10.02,5.69,0.00,0.00,6.42,0.00,19.71,0.00,0.00
162,PI 38:3,8.18,4.78,1.08,1.53,0.00,1.61,2.35,8.08,2.30,...,1.02,5.00,0.00,1.80,0.00,1.90,1.23,4.80,0.52,3.91
163,PI 38:4,48.70,32.24,39.87,33.49,25.70,29.44,42.01,50.75,44.01,...,40.40,52.34,35.36,28.07,22.35,33.45,35.42,56.77,21.42,35.44

In [105]:
df_D10.to_csv(
    '/Users/loictalignani/research/project/lipidomics/data/lipidsig/Lipid_abundance_data_D10.tsv', sep="\t", index=False)

In [106]:
df_D60 = df[["feature"] + df.filter(regex="D60$").columns.tolist()]
column_order = [
    'BS-064', 'JV-035', 'JV-048', 'KT-515', 'KT-926', 'JV-148', 'JV-157',
    'KT-193', 'KT-247', 'KT-312', 'KT-347', 'KT-352', 'KT-417', 'KT-434',
    'KT-522', 'KT-525', 'KT-565', 'KT-612', 'KT-705', 'KT-718', 'JV-071',
    'BS-082', 'BS-336', 'BS-346', 'BS-351', 'BS-364', 'BS-377', 'JV-138',
    'KT-313', 'KT-412', 'KT-445', 'KT-537', 'KT-538', 'KT-539', 'KT-663',
    'KT-695', 'KT-716', 'KT-723', 'KT-771', 'KT-805', 'KT-880', 'KT-974',
    'BS-671'
]
# Ajoute le suffixe D0 à chaque élément de la liste
column_order_d60 = [col + 'D60' for col in column_order]
conditions_column = df_D60.pop('feature')
df_D60 = df_D60.reindex(column_order_d60, axis=1)
if conditions_column is not None:
    df_D60.insert(0, 'feature', conditions_column)
df_D60.fillna(0, inplace=True)
df_D60 = df_D60.replace(',', '.', regex=True)
df_D60

,feature,BS-064D60,JV-035D60,JV-048D60,KT-515D60,KT-926D60,JV-148D60,JV-157D60,KT-193D60,KT-247D60,...,KT-539D60,KT-663D60,KT-695D60,KT-716D60,KT-723D60,KT-771D60,KT-805D60,KT-880D60,KT-974D60,BS-671D60
0,DG 30:0,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.83,0.00,0.00,0.00,0.00
1,DG 32:0,0.95,0.43,0.0,0.37,0.39,0.37,0.46,0.78,0.82,...,0.00,0.44,0.00,0.63,0.35,2.42,0.72,2.56,0.48,0.66
2,DG 32:1,0.00,0.00,0.0,0.00,0.00,0.35,0.00,0.92,0.78,...,0.00,0.00,0.00,0.49,0.59,2.33,0.51,0.00,0.00,0.00
3,DG 34:1,4.79,2.95,0.0,2.12,1.75,1.81,2.71,3.59,5.68,...,1.61,2.12,1.97,3.80,2.76,9.16,3.99,5.65,2.57,3.12
4,DG 34:3,0.00,0.00,0.0,0.00,0.00,0.16,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.57,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,PI 34:2,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,3.27,0.00,0.00
160,PI 36:2,4.32,6.36,0.0,4.79,0.00,1.82,0.00,4.72,3.03,...,0.00,3.14,0.00,3.67,0.00,4.82,3.95,9.59,0.00,5.06
161,PI 36:4,0.00,2.57,0.0,3.22,0.00,1.40,0.00,6.37,0.00,...,0.00,0.00,0.00,4.13,0.00,5.93,2.91,6.25,0.00,0.00
162,PI 38:3,0.00,1.97,0.0,0.00,0.00,0.68,0.00,1.03,0.60,...,0.00,0.00,0.00,2.18,0.00,2.19,4.65,7.66,0.63,0.00
163,PI 38:4,24.48,31.64,0.0,35.02,28.14,19.04,29.45,28.26,21.84,...,30.19,21.43,34.55,29.93,19.67,50.20,18.38,15.31,15.08,29.26

In [108]:
df_D60.to_csv('/Users/loictalignani/research/project/lipidomics/data/lipidsig/Lipid_abundance_data_D60.tsv', sep="\t", index=False)