# Calculate Log2 Fold-Change
Normalize dataset

In [54]:
import pandas as pd
import numpy as np

In [55]:
# Charger le fichier CSV
df = pd.read_csv(
    "/Users/loictalignani/research/project/lipidomics/data/pretreatment/MISSE_Global_Lipidomics_results_all_for_log2FC_calculation.tsv", sep="\t")
df

,feature,BS-064D0,BS-064D03,BS-064D10,BS-064D60,BS-082D0,BS-082D03,BS-082D10,BS-082D60,BS-336D0,...,KT-926D0,KT-926D03,KT-926D10,KT-926D60,KT-974D0,KT-974D03,KT-974D10,KT-974D60,Unnamed: 161,Unnamed: 162
0,DG 30:0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN
1,DG 32:0,0.75,0.78,1.41,0.95,0.53,0.00,0.86,0.51,0.00,...,1.15,0.91,0.90,0.39,0.00,0.41,0.00,0.48,NaN,NaN
2,DG 32:1,0.00,0.86,1.73,0.00,0.37,0.00,0.76,0.48,0.00,...,1.15,0.37,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN
3,DG 34:1,2.27,4.10,5.12,4.79,2.40,1.97,3.17,1.78,1.68,...,8.03,2.95,4.08,1.75,0.88,2.15,1.96,2.57,NaN,NaN
4,DG 34:3,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.69,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,PI 34:2,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN
160,PI 36:2,0.00,3.57,4.47,4.32,0.00,0.00,0.00,0.00,0.00,...,2.20,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN
161,PI 36:4,0.00,4.34,9.45,0.00,0.00,0.00,0.00,0.00,0.00,...,3.63,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN
162,PI 38:3,0.00,0.61,8.18,0.00,0.00,0.00,0.00,0.26,0.00,...,0.52,0.00,0.00,0.00,0.00,0.00,0.52,0.63,NaN,NaN
163,PI 38:4,23.40,31.29,48.70,24.48,5.83,8.92,13.71,22.17,15.85,...,14.42,11.38,25.70,28.14,2.79,17.33,21.42,15.08,NaN,NaN

In [56]:
df.dtypes

feature          object
BS-064D0        float64
BS-064D03       float64
BS-064D10       float64
BS-064D60       float64
                 ...
KT-974D03       float64
KT-974D10       float64
KT-974D60       float64
Unnamed: 161    float64
Unnamed: 162    float64
Length: 163, dtype: object

In [57]:
# Extraire les noms de colonnes correspondant aux échantillons
sample_columns = [
    col for col in df.columns if "D0" in col or "D03" in col or "D10" in col or "D60" in col]

In [58]:
# Créer de nouvelles colonnes avec le log2 fold-change
for col in sample_columns:
    patient_id = col[:-2]  # Retirer le suffixe temporel (D0, D03, etc.)
    if f"{patient_id}D60" in df.columns:  # Vérifier que D60 existe pour ce patient
        df[f"log2FC_D0-{patient_id}"] = np.log2(
            (df[f"{patient_id}D0"] + 1) / (df[f"{patient_id}D60"] + 1))
        df[f"log2FC_D03-{patient_id}"] = np.log2(
            (df[f"{patient_id}D03"] + 1) / (df[f"{patient_id}D60"] + 1))
        df[f"log2FC_D10-{patient_id}"] = np.log2(
            (df[f"{patient_id}D10"] + 1) / (df[f"{patient_id}D60"] + 1))

/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_61731/846847376.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"log2FC_D10-{patient_id}"] = np.log2(
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_61731/846847376.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"log2FC_D0-{patient_id}"] = np.log2(
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_61731/846847376.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"log2FC_D03-{patient_id}"] = np.log2(
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_61731/846847376.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"log2FC_D10-{patient_id}"] = np.log2(
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_61731/846847376.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"log2FC_D0-{patient_id}"] = np.log2(
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_61731/846847376.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"log2FC_D03-{patient_id}"] = np.log2(
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_61731/846847376.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"log2FC_D10-{patient_id}"] = np.log2(
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_61731/846847376.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"log2FC_D0-{patient_id}"] = np.log2(
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_61731/846847376.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"log2FC_D03-{patient_id}"] = np.log2(
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_61731/846847376.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"log2FC_D10-{patient_id}"] = np.log2(
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_61731/846847376.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"log2FC_D0-{patient_id}"] = np.log2(
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_61731/846847376.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"log2FC_D03-{patient_id}"] = np.log2(
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_61731/846847376.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"log2FC_D10-{patient_id}"] = np.log2(
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_61731/846847376.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"log2FC_D0-{patient_id}"] = np.log2(
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_61731/846847376.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"log2FC_D03-{patient_id}"] = np.log2(
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_61731/846847376.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"log2FC_D10-{patient_id}"] = np.log2(
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_61731/846847376.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"log2FC_D0-{patient_id}"] = np.log2(
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_61731/846847376.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"log2FC_D03-{patient_id}"] = np.log2(
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_61731/846847376.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"log2FC_D10-{patient_id}"] = np.log2(
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_61731/846847376.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"log2FC_D0-{patient_id}"] = np.log2(
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_61731/846847376.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"log2FC_D03-{patient_id}"] = np.log2(
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_61731/846847376.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"log2FC_D10-{patient_id}"] = np.log2(

In [59]:
df

,feature,BS-064D0,BS-064D03,BS-064D10,BS-064D60,BS-082D0,BS-082D03,BS-082D10,BS-082D60,BS-336D0,...,log2FC_D10-KT-805,log2FC_D0-KT-880,log2FC_D03-KT-880,log2FC_D10-KT-880,log2FC_D0-KT-926,log2FC_D03-KT-926,log2FC_D10-KT-926,log2FC_D0-KT-974,log2FC_D03-KT-974,log2FC_D10-KT-974
0,DG 30:0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,DG 32:0,0.75,0.78,1.41,0.95,0.53,0.00,0.86,0.51,0.00,...,1.004188,-0.983880,-0.861024,-0.290858,0.629252,0.458488,0.450915,-0.565597,-0.069902,-0.565597
2,DG 32:1,0.00,0.86,1.73,0.00,0.37,0.00,0.76,0.48,0.00,...,1.009523,0.000000,0.000000,1.416840,1.104337,0.454176,0.000000,0.000000,0.000000,0.000000
3,DG 34:1,2.27,4.10,5.12,4.79,2.40,1.97,3.17,1.78,1.68,...,1.230629,-0.402796,-0.830316,0.708926,1.715294,0.522421,0.885397,-0.925191,-0.180572,-0.270327
4,DG 34:3,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.622930,0.000000,0.000000,0.000000,0.757023,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,PI 34:2,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.000000,-2.094236,-2.094236,0.471361,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
160,PI 36:2,0.00,3.57,4.47,4.32,0.00,0.00,0.00,0.00,0.00,...,-0.026472,-3.404631,-3.404631,-0.071207,1.678072,0.000000,0.000000,0.000000,0.000000,0.000000
161,PI 36:4,0.00,4.34,9.45,0.00,0.00,0.00,0.00,0.00,0.00,...,-1.967169,-2.857981,-2.857981,1.514275,2.211012,0.000000,0.000000,0.000000,0.000000,0.000000
162,PI 38:3,0.00,0.61,8.18,0.00,0.00,0.00,0.00,0.26,0.00,...,-1.341207,-3.114367,-3.114367,-0.578314,0.604071,0.000000,0.000000,-0.704872,-0.704872,-0.100801
163,PI 38:4,23.40,31.29,48.70,24.48,5.83,8.92,13.71,22.17,15.85,...,0.910162,-0.758652,-1.581429,1.824564,-0.918198,-1.234990,-0.126161,-2.084998,0.188939,0.479519

In [60]:
# Sauvegarder le nouveau fichier
output_file = "/Users/loictalignani/research/project/lipidomics/data/pretreatment/MISSE_Global_Lipidomics_results_all_with_log2FC.tsv"
df.to_csv(output_file, sep="\t", index=False)

print(f"Fichier enregistré : {output_file}")

Fichier enregistré : /Users/loictalignani/research/project/lipidomics/data/pretreatment/MISSE_Global_Lipidomics_results_all_with_log2FC.tsv