# Normalization by simple ratio
Normalize dataset

In [1]:
import pandas as pd
import numpy as np
from scipy.stats import rankdata

In [2]:
# Charger le fichier CSV
df = pd.read_csv(
    "/Users/loictalignani/research/project/lipidomics/data/pretreatment/MISSE_Global_Lipidomics_results_all_for_log2FC_calculation.tsv", sep="\t")
df

,feature,BS-064D0,BS-064D03,BS-064D10,BS-064D60,BS-082D0,BS-082D03,BS-082D10,BS-082D60,BS-336D0,...,KT-880D10,KT-880D60,KT-926D0,KT-926D03,KT-926D10,KT-926D60,KT-974D0,KT-974D03,KT-974D10,KT-974D60
0,DG 30:0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
1,DG 32:0,0.75,0.78,1.41,0.95,0.53,0.00,0.86,0.51,0.00,...,1.91,2.56,1.15,0.91,0.90,0.39,0.00,0.41,0.00,0.48
2,DG 32:1,0.00,0.86,1.73,0.00,0.37,0.00,0.76,0.48,0.00,...,1.67,0.00,1.15,0.37,0.00,0.00,0.00,0.00,0.00,0.00
3,DG 34:1,2.27,4.10,5.12,4.79,2.40,1.97,3.17,1.78,1.68,...,9.87,5.65,8.03,2.95,4.08,1.75,0.88,2.15,1.96,2.57
4,DG 34:3,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.69,0.00,0.00,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,PI 34:2,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,4.92,3.27,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
160,PI 36:2,0.00,3.57,4.47,4.32,0.00,0.00,0.00,0.00,0.00,...,9.08,9.59,2.20,0.00,0.00,0.00,0.00,0.00,0.00,0.00
161,PI 36:4,0.00,4.34,9.45,0.00,0.00,0.00,0.00,0.00,0.00,...,19.71,6.25,3.63,0.00,0.00,0.00,0.00,0.00,0.00,0.00
162,PI 38:3,0.00,0.61,8.18,0.00,0.00,0.00,0.00,0.26,0.00,...,4.80,7.66,0.52,0.00,0.00,0.00,0.00,0.00,0.52,0.63
163,PI 38:4,23.40,31.29,48.70,24.48,5.83,8.92,13.71,22.17,15.85,...,56.77,15.31,14.42,11.38,25.70,28.14,2.79,17.33,21.42,15.08

In [3]:
offset = 1  # Offset à ajouter pour éviter la division par zéro

In [4]:
# Identifier les patients en récupérant les préfixes des colonnes
patients = set(col.split('D')[0]
               for col in df.columns[1:])  # Exclure 'feature'

In [5]:
# Appliquer l'offset à toutes les colonnes de patients
for patient in patients:
    patient_cols = [col for col in df.columns if col.startswith(patient)]
    # Ajout de l'offset pour toutes les colonnes du patient
    df[patient_cols] += offset

In [6]:
# Calculer les ratios et créer les nouvelles colonnes
for patient in patients:
    d0_col, d3_col, d10_col, d60_col = f"{patient}D0", f"{patient}D03", f"{patient}D10", f"{patient}D60"

    if d3_col in df.columns:
        df[f"{patient}_D0_D3"] = df[d0_col] / df[d3_col]
        df[f"{patient}_D3_D10"] = df[d3_col] / df[d10_col]

/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D3"] = df[d0_col] / df[d3_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D10"] = df[d3_col] / df[d10_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D3"] = df[d0_col] / df[d3_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D10"] = df[d3_col] / df[d10_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D3"] = df[d0_col] / df[d3_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D10"] = df[d3_col] / df[d10_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D3"] = df[d0_col] / df[d3_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D10"] = df[d3_col] / df[d10_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D3"] = df[d0_col] / df[d3_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D10"] = df[d3_col] / df[d10_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D3"] = df[d0_col] / df[d3_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D10"] = df[d3_col] / df[d10_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D3"] = df[d0_col] / df[d3_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D10"] = df[d3_col] / df[d10_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D3"] = df[d0_col] / df[d3_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D10"] = df[d3_col] / df[d10_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D3"] = df[d0_col] / df[d3_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D10"] = df[d3_col] / df[d10_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D3"] = df[d0_col] / df[d3_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D10"] = df[d3_col] / df[d10_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D3"] = df[d0_col] / df[d3_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D10"] = df[d3_col] / df[d10_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D3"] = df[d0_col] / df[d3_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D10"] = df[d3_col] / df[d10_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D3"] = df[d0_col] / df[d3_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D10"] = df[d3_col] / df[d10_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D3"] = df[d0_col] / df[d3_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D10"] = df[d3_col] / df[d10_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D3"] = df[d0_col] / df[d3_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D10"] = df[d3_col] / df[d10_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D3"] = df[d0_col] / df[d3_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D10"] = df[d3_col] / df[d10_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D3"] = df[d0_col] / df[d3_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D10"] = df[d3_col] / df[d10_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D3"] = df[d0_col] / df[d3_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D10"] = df[d3_col] / df[d10_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D3"] = df[d0_col] / df[d3_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D10"] = df[d3_col] / df[d10_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D3"] = df[d0_col] / df[d3_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D10"] = df[d3_col] / df[d10_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D3"] = df[d0_col] / df[d3_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D10"] = df[d3_col] / df[d10_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D3"] = df[d0_col] / df[d3_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D10"] = df[d3_col] / df[d10_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D3"] = df[d0_col] / df[d3_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D10"] = df[d3_col] / df[d10_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D3"] = df[d0_col] / df[d3_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69151/266155494.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D10"] = df[d3_col] / df[d10_col]

In [7]:
df

,feature,BS-064D0,BS-064D03,BS-064D10,BS-064D60,BS-082D0,BS-082D03,BS-082D10,BS-082D60,BS-336D0,...,BS-346_D0_D3,BS-346_D3_D10,KT-705_D0_D3,KT-705_D3_D10,BS-082_D0_D3,BS-082_D3_D10,JV-148_D0_D3,JV-148_D3_D10,KT-347_D0_D3,KT-347_D3_D10
0,DG 30:0,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,...,1.000000,1.000000,1.000000,0.653595,1.000000,1.000000,1.000000,0.632911,1.000000,1.000000
1,DG 32:0,1.75,1.78,2.41,1.95,1.53,1.00,1.86,1.51,1.00,...,0.384615,0.463458,1.245033,0.702326,1.530000,0.537634,0.507614,0.665541,1.050314,1.052980
2,DG 32:1,1.00,1.86,2.73,1.00,1.37,1.00,1.76,1.48,1.00,...,0.657895,0.401055,1.000000,0.431034,1.370000,0.568182,0.357143,0.930233,0.724638,0.938776
3,DG 34:1,3.27,5.10,6.12,5.79,3.40,2.97,4.17,2.78,2.68,...,0.255846,0.591057,1.395770,0.817284,1.144781,0.712230,0.383629,1.310078,1.272947,0.943052
4,DG 34:3,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,...,1.000000,0.578035,1.000000,1.000000,1.000000,1.000000,0.543478,1.343066,1.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,PI 34:2,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,...,1.000000,0.190476,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
160,PI 36:2,1.00,4.57,5.47,5.32,1.00,1.00,1.00,1.00,1.00,...,0.080000,1.293996,0.770642,1.030246,1.000000,1.000000,4.610000,1.000000,0.156740,6.380000
161,PI 36:4,1.00,5.34,10.45,1.00,1.00,1.00,1.00,1.00,1.00,...,1.000000,0.056980,1.000000,0.175131,1.000000,1.000000,1.000000,1.000000,1.000000,0.250627
162,PI 38:3,1.00,1.61,9.18,1.00,1.00,1.00,1.00,1.26,1.00,...,1.000000,0.173913,1.000000,0.581395,1.000000,1.000000,1.000000,0.383142,1.000000,1.000000
163,PI 38:4,24.40,32.29,49.70,25.48,6.83,9.92,14.71,23.17,16.85,...,0.187487,1.092854,0.586145,0.850421,0.688508,0.674371,0.827292,0.616294,0.443471,0.781239

In [8]:
# Sauvegarder le nouveau fichier
output_file = "/Users/loictalignani/research/project/lipidomics/data/pretreatment/MISSE_Global_Lipidomics_results_D0vsD3_D3vsD10.tsv"
df.to_csv(output_file, sep="\t", index=False)

print(f"Fichier enregistré : {output_file}")

Fichier enregistré : /Users/loictalignani/research/project/lipidomics/data/pretreatment/MISSE_Global_Lipidomics_results_D0vsD3_D3vsD10.tsv

In [9]:
# Extraire les nouvelles colonnes dans trois DataFrames distincts
columns_D0_D3 = ["feature"] + \
    [col for col in df.columns if col.endswith("_D0_D3")]
columns_D3_D10 = ["feature"] + \
    [col for col in df.columns if col.endswith("_D3_D10")]

In [10]:
df_D0_D3 = df[columns_D0_D3]
df_D3_D10 = df[columns_D3_D10]

In [11]:
outfile = "/Users/loictalignani/research/project/lipidomics/data/lipidsig_datasets/Ratio_lipid_abundance_data_D0vsD3.tsv"
df_D0_D3.to_csv(outfile, sep="\t", index=False)

In [13]:
df_D0_D3.shape

(164, 41)

In [12]:
outfile = "/Users/loictalignani/research/project/lipidomics/data/lipidsig_datasets/Ratio_lipid_abundance_data_D3vsD10.tsv"
df_D3_D10.to_csv(outfile, sep="\t", index=False)

In [14]:
df_D3_D10.shape

(164, 41)