# Normalization by simple ratio
Normalize dataset

In [1]:
import pandas as pd
import numpy as np
from scipy.stats import rankdata

In [47]:
# Charger le fichier CSV
df = pd.read_csv(
    "/Users/loictalignani/research/project/lipidomics/data/pretreatment/MISSE_Global_Lipidomics_results_all_for_log2FC_calculation.tsv", sep="\t")
df

,feature,BS-064D0,BS-064D03,BS-064D10,BS-064D60,BS-082D0,BS-082D03,BS-082D10,BS-082D60,BS-336D0,...,KT-880D10,KT-880D60,KT-926D0,KT-926D03,KT-926D10,KT-926D60,KT-974D0,KT-974D03,KT-974D10,KT-974D60
0,DG 30:0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
1,DG 32:0,0.75,0.78,1.41,0.95,0.53,0.00,0.86,0.51,0.00,...,1.91,2.56,1.15,0.91,0.90,0.39,0.00,0.41,0.00,0.48
2,DG 32:1,0.00,0.86,1.73,0.00,0.37,0.00,0.76,0.48,0.00,...,1.67,0.00,1.15,0.37,0.00,0.00,0.00,0.00,0.00,0.00
3,DG 34:1,2.27,4.10,5.12,4.79,2.40,1.97,3.17,1.78,1.68,...,9.87,5.65,8.03,2.95,4.08,1.75,0.88,2.15,1.96,2.57
4,DG 34:3,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.69,0.00,0.00,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,PI 34:2,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,4.92,3.27,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
160,PI 36:2,0.00,3.57,4.47,4.32,0.00,0.00,0.00,0.00,0.00,...,9.08,9.59,2.20,0.00,0.00,0.00,0.00,0.00,0.00,0.00
161,PI 36:4,0.00,4.34,9.45,0.00,0.00,0.00,0.00,0.00,0.00,...,19.71,6.25,3.63,0.00,0.00,0.00,0.00,0.00,0.00,0.00
162,PI 38:3,0.00,0.61,8.18,0.00,0.00,0.00,0.00,0.26,0.00,...,4.80,7.66,0.52,0.00,0.00,0.00,0.00,0.00,0.52,0.63
163,PI 38:4,23.40,31.29,48.70,24.48,5.83,8.92,13.71,22.17,15.85,...,56.77,15.31,14.42,11.38,25.70,28.14,2.79,17.33,21.42,15.08

In [48]:
offset = 1  # Offset à ajouter pour éviter la division par zéro

In [49]:
# Identifier les patients en récupérant les préfixes des colonnes
patients = set(col.split('D')[0]
               for col in df.columns[1:])  # Exclure 'feature'

In [50]:
# Appliquer l'offset à toutes les colonnes de patients
for patient in patients:
    patient_cols = [col for col in df.columns if col.startswith(patient)]
    # Ajout de l'offset pour toutes les colonnes du patient
    df[patient_cols] += offset

In [51]:
# Calculer les ratios et créer les nouvelles colonnes
for patient in patients:
    d0_col, d3_col, d10_col, d60_col = f"{patient}D0", f"{patient}D03", f"{patient}D10", f"{patient}D60"

    if d60_col in df.columns:
        df[f"{patient}_D0_D60"] = df[d0_col] / df[d60_col]
        df[f"{patient}_D3_D60"] = df[d3_col] / df[d60_col]
        df[f"{patient}_D10_D60"] = df[d10_col] / df[d60_col]

/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D60"] = df[d0_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D60"] = df[d3_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D10_D60"] = df[d10_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D60"] = df[d0_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D60"] = df[d3_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D10_D60"] = df[d10_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D60"] = df[d0_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D60"] = df[d3_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D10_D60"] = df[d10_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D60"] = df[d0_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D60"] = df[d3_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D10_D60"] = df[d10_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D60"] = df[d0_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D60"] = df[d3_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D10_D60"] = df[d10_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D60"] = df[d0_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D60"] = df[d3_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D10_D60"] = df[d10_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D60"] = df[d0_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D60"] = df[d3_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D10_D60"] = df[d10_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D60"] = df[d0_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D60"] = df[d3_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D10_D60"] = df[d10_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D60"] = df[d0_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D60"] = df[d3_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D10_D60"] = df[d10_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D60"] = df[d0_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D60"] = df[d3_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D10_D60"] = df[d10_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D60"] = df[d0_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D60"] = df[d3_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D10_D60"] = df[d10_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D60"] = df[d0_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D60"] = df[d3_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D10_D60"] = df[d10_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D60"] = df[d0_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D60"] = df[d3_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D10_D60"] = df[d10_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D60"] = df[d0_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D60"] = df[d3_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D10_D60"] = df[d10_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D60"] = df[d0_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D60"] = df[d3_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D10_D60"] = df[d10_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D0_D60"] = df[d0_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D3_D60"] = df[d3_col] / df[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_47179/657889009.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{patient}_D10_D60"] = df[d10_col] / df[d60_col]

In [52]:
df

,feature,BS-064D0,BS-064D03,BS-064D10,BS-064D60,BS-082D0,BS-082D03,BS-082D10,BS-082D60,BS-336D0,...,JV-148_D10_D60,BS-346_D0_D60,BS-346_D3_D60,BS-346_D10_D60,KT-663_D0_D60,KT-663_D3_D60,KT-663_D10_D60,KT-695_D0_D60,KT-695_D3_D60,KT-695_D10_D60
0,DG 30:0,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,...,1.580000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000
1,DG 32:0,1.75,1.78,2.41,1.95,1.53,1.00,1.86,1.51,1.00,...,2.160584,0.458716,1.192661,2.573394,0.694444,1.131944,1.979167,1.000000,1.95000,1.920000
2,DG 32:1,1.00,1.86,2.73,1.00,1.37,1.00,1.76,1.48,1.00,...,2.229630,0.606061,0.921212,2.296970,1.000000,1.000000,2.890000,1.000000,1.00000,1.620000
3,DG 34:1,3.27,5.10,6.12,5.79,3.40,2.97,4.17,2.78,2.68,...,2.754448,0.259414,1.013947,1.715481,0.506410,1.064103,2.750000,0.757576,1.16835,1.932660
4,DG 34:3,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,...,1.181034,1.000000,1.000000,1.730000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,PI 34:2,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,...,1.000000,1.000000,1.000000,5.250000,1.000000,1.000000,4.510000,1.000000,1.00000,1.000000
160,PI 36:2,1.00,4.57,5.47,5.32,1.00,1.00,1.00,1.00,1.00,...,0.354610,0.152439,1.905488,1.472561,0.241546,0.833333,2.094203,1.000000,4.77000,1.000000
161,PI 36:4,1.00,5.34,10.45,1.00,1.00,1.00,1.00,1.00,1.00,...,0.416667,1.000000,1.000000,17.550000,1.000000,1.000000,11.020000,1.000000,1.00000,6.690000
162,PI 38:3,1.00,1.61,9.18,1.00,1.00,1.00,1.00,1.26,1.00,...,1.553571,1.000000,1.000000,5.750000,1.000000,1.000000,6.000000,1.000000,1.00000,1.000000
163,PI 38:4,24.40,32.29,49.70,25.48,6.83,9.92,14.71,23.17,16.85,...,1.518962,0.266265,1.420178,1.299513,0.044583,0.504235,2.378065,0.135302,0.44782,1.022785

In [53]:
# Sauvegarder le nouveau fichier
output_file = "/Users/loictalignani/research/project/lipidomics/data/pretreatment/MISSE_Global_Lipidomics_results_all_ratios.tsv"
df.to_csv(output_file, sep="\t", index=False)

print(f"Fichier enregistré : {output_file}")

Fichier enregistré : /Users/loictalignani/research/project/lipidomics/data/pretreatment/MISSE_Global_Lipidomics_results_all_ratios.tsv

In [54]:
# Extraire les nouvelles colonnes dans trois DataFrames distincts
columns_D0_D60 = ["feature"] + \
    [col for col in df.columns if col.endswith("_D0_D60")]
columns_D3_D60 = ["feature"] + \
    [col for col in df.columns if col.endswith("_D3_D60")]
columns_D10_D60 = ["feature"] + \
    [col for col in df.columns if col.endswith("_D10_D60")]

In [55]:
df_D0_D60 = df[columns_D0_D60]
df_D3_D60 = df[columns_D3_D60]
df_D10_D60 = df[columns_D10_D60]

In [58]:
outfile = "/Users/loictalignani/research/project/lipidomics/data/lipidsig_datasets/Ratio_lipid_abundance_data_D0.tsv"
df_D0_D60.to_csv(outfile, sep="\t", index=False)

In [59]:
outfile = "/Users/loictalignani/research/project/lipidomics/data/lipidsig_datasets/Ratio_lipid_abundance_data_D3.tsv"
df_D3_D60.to_csv(outfile, sep="\t", index=False)

In [60]:
outfile = "/Users/loictalignani/research/project/lipidomics/data/lipidsig_datasets/Ratio_lipid_abundance_data_D10.tsv"
df_D10_D60.to_csv(outfile, sep="\t", index=False)