# Oxylipin pretreatment
Normalize dataset by division /D60 values

In [2]:
import pandas as pd
import numpy as np

In [42]:
# Charger le fichier Excel
file_path = "/Users/loictalignani/research/project/lipidomics/data/raw_data/oxylipines_div_1.xlsx"
xls = pd.ExcelFile(file_path)

# Charger les données des onglets
species = pd.read_excel(xls, sheet_name="data")
patient_data = pd.read_excel(xls, sheet_name="order")

In [43]:
species

,feature,KT-312D10,BS-364D0,KT-412D60,KT-974D03,JV-138D0,BS-671D03,KT-723D10,KT-705D60,KT-434D03,...,KT-537D0,KT-313D03,JV-035D10,BS-377D03,KT-880D60,KT-434D0,JV-035D03,KT-412D0,BS-671D10,KT-974D60
0,FA 18:2;O,14.865283,21.497567,10.846900,89.558500,35.857650,27.483217,14.128983,7.418400,28.676300,...,22.163550,10.877283,23.700650,39.977683,30.411150,13.210950,20.561650,13.653850,13.947750,17.897417
1,FA 18:1;O2,1.970350,2.820100,4.621233,13.864950,2.510167,0.598733,2.749933,1.201033,2.399867,...,5.272700,1.531750,3.214550,0.706083,4.146717,11.880800,4.403850,7.940333,7.006133,1.669117
2,FA 18:3;O,1.736617,0.718367,0.000000,6.359050,0.563050,0.182233,0.134317,0.136050,0.545383,...,0.309400,0.456867,0.318400,0.863067,0.718200,0.000000,0.765183,0.825683,0.135683,0.185667
3,FA 18:1;O3,0.365767,0.308683,0.470983,5.466883,0.000000,0.198700,0.146267,0.245300,0.929750,...,1.623800,0.653533,0.445483,0.000000,0.856550,2.213133,0.252400,0.224117,0.355400,0.000000
4,FA 20:4;O,0.762267,2.258633,0.000000,2.601133,0.828633,1.540600,2.979100,1.694300,2.106700,...,2.183283,0.411917,0.421850,1.616133,4.455650,10.225200,0.441017,1.487100,0.422867,0.000000
5,FA 20:5,3.551567,1.879733,1.222883,7.482233,2.134117,1.470550,0.862850,0.690883,0.357567,...,1.613083,0.573533,1.269017,9.375067,2.092650,0.362000,0.216750,0.373617,1.511600,0.186950
6,FA 20:4;O3,0.464583,0.901950,1.214350,5.653617,1.092117,2.030550,0.680467,0.000000,0.241933,...,2.012467,0.158750,0.787333,2.286550,0.741083,0.284450,0.000000,0.000000,0.854800,0.122467
7,FA 20:3;O4,11.630633,21.740717,3.318200,56.447400,15.070783,15.813233,13.514317,12.899650,7.437883,...,35.334533,16.159983,21.632583,14.141217,28.506433,95.715767,5.948583,8.394733,5.458133,9.663317
8,FA 20:5;O,0.000000,0.114383,0.000000,0.262167,0.235583,0.143267,1.361417,0.300450,0.000000,...,0.108033,0.000000,0.192233,0.275617,-0.008483,0.072700,-0.013967,0.005250,0.000000,0.000000
9,FA 22:6;O,60.110000,223.869817,28.000933,162.637600,122.104650,143.193700,551.660667,214.540283,431.072117,...,173.838250,69.858133,189.062833,153.918700,300.142383,199.861250,282.957033,218.716583,83.043167,78.768317

In [44]:
species.dtypes

feature       object
KT-312D10    float64
BS-364D0     float64
KT-412D60    float64
KT-974D03    float64
              ...
KT-434D0     float64
JV-035D03    float64
KT-412D0     float64
BS-671D10    float64
KT-974D60    float64
Length: 166, dtype: object

In [45]:
# Extraire les noms de colonnes correspondant aux échantillons
sample_columns = [
    col for col in species.columns if "D0" in col or "D03" in col or "D10" in col or "D60" in col]

In [46]:
# Identifier les patients en récupérant les préfixes des colonnes
patients = set(col.split('D')[0]
               for col in species.columns[1:])  # Exclure 'feature'
patients

{'BS-064',
 'BS-082',
 'BS-336',
 'BS-346',
 'BS-351',
 'BS-364',
 'BS-377',
 'BS-671',
 'JV-035',
 'JV-048',
 'JV-138',
 'JV-148',
 'JV-157',
 'KT-193',
 'KT-247',
 'KT-312',
 'KT-313',
 'KT-347',
 'KT-352',
 'KT-412',
 'KT-417',
 'KT-434',
 'KT-445',
 'KT-515',
 'KT-522',
 'KT-525',
 'KT-537',
 'KT-538',
 'KT-539',
 'KT-565',
 'KT-612',
 'KT-663',
 'KT-695',
 'KT-705',
 'KT-716',
 'KT-718',
 'KT-723',
 'KT-771',
 'KT-805',
 'KT-880',
 'KT-926',
 'KT-927',
 'KT-928',
 'KT-974'}

In [47]:
offset = 1  # Offset à ajouter pour éviter la division par zéro

In [48]:
# Appliquer l'offset à toutes les colonnes de patients
for patient in patients:
    patient_cols = [col for col in species.columns if col.startswith(patient)]
    # Ajout de l'offset pour toutes les colonnes du patient
    species[patient_cols] += offset

In [49]:
# Calculer les ratios et créer les nouvelles colonnes
for patient in patients:
    d0_col, d3_col, d10_col, d60_col = f"{patient}D0", f"{patient}D03", f"{patient}D10", f"{patient}D60"

    if d60_col in species.columns:
        species[f"{patient}_D0_D60"] = species[d0_col] / species[d60_col]
        species[f"{patient}_D3_D60"] = species[d3_col] / species[d60_col]
        species[f"{patient}_D10_D60"] = species[d10_col] / species[d60_col]

/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D0_D60"] = species[d0_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D3_D60"] = species[d3_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D10_D60"] = species[d10_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D0_D60"] = species[d0_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D3_D60"] = species[d3_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D10_D60"] = species[d10_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D0_D60"] = species[d0_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D3_D60"] = species[d3_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D10_D60"] = species[d10_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D0_D60"] = species[d0_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D3_D60"] = species[d3_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D10_D60"] = species[d10_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D0_D60"] = species[d0_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D3_D60"] = species[d3_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D10_D60"] = species[d10_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D0_D60"] = species[d0_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D3_D60"] = species[d3_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D10_D60"] = species[d10_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D0_D60"] = species[d0_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D3_D60"] = species[d3_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D10_D60"] = species[d10_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D0_D60"] = species[d0_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D3_D60"] = species[d3_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D10_D60"] = species[d10_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D0_D60"] = species[d0_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D3_D60"] = species[d3_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D10_D60"] = species[d10_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D0_D60"] = species[d0_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D3_D60"] = species[d3_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D10_D60"] = species[d10_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D0_D60"] = species[d0_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D3_D60"] = species[d3_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D10_D60"] = species[d10_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D0_D60"] = species[d0_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D3_D60"] = species[d3_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D10_D60"] = species[d10_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D0_D60"] = species[d0_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D3_D60"] = species[d3_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D10_D60"] = species[d10_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D0_D60"] = species[d0_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D3_D60"] = species[d3_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D10_D60"] = species[d10_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D0_D60"] = species[d0_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D3_D60"] = species[d3_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D10_D60"] = species[d10_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_69822/1705873891.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D0_D60"] = species[d0_col] / species[d60_col]

In [50]:
species

,feature,KT-312D10,BS-364D0,KT-412D60,KT-974D03,JV-138D0,BS-671D03,KT-723D10,KT-705D60,KT-434D03,...,KT-771_D10_D60,KT-525_D0_D60,KT-525_D3_D60,KT-525_D10_D60,KT-522_D0_D60,KT-522_D3_D60,KT-522_D10_D60,JV-035_D0_D60,JV-035_D3_D60,JV-035_D10_D60
0,FA 18:2;O,15.865283,22.497567,11.846900,90.558500,36.857650,28.483217,15.128983,8.418400,29.676300,...,0.581166,5.110580,1.550305,0.917925,0.445078,0.457385,0.553896,2.417398,1.212372,1.388872
1,FA 18:1;O2,2.970350,3.820100,5.621233,14.864950,3.510167,1.598733,3.749933,2.201033,3.399867,...,1.121816,1.145796,2.472463,0.842387,0.751645,0.632941,0.929972,4.050825,2.308006,1.800051
2,FA 18:3;O,2.736617,1.718367,1.000000,7.359050,1.563050,1.182233,1.134317,1.136050,1.545383,...,0.907302,0.850825,1.055977,0.860235,0.212265,0.237492,0.488955,0.823610,1.146322,0.856178
3,FA 18:1;O3,1.365767,1.308683,1.470983,6.466883,1.000000,1.198700,1.146267,1.245300,1.929750,...,0.925990,0.900078,1.010105,0.720072,0.196308,0.185942,0.234755,0.973298,0.795284,0.917893
4,FA 20:4;O,1.762267,3.258633,1.000000,3.601133,1.828633,2.540600,3.979100,2.694300,3.106700,...,2.126200,3.011517,1.000000,1.000000,0.347661,1.053076,0.351478,3.530908,0.920376,0.908134
5,FA 20:5,4.551567,2.879733,2.222883,8.482233,3.134117,2.470550,1.862850,1.690883,1.357567,...,0.743654,0.505259,0.847315,0.520489,0.619953,0.160251,0.413715,0.746407,0.316347,0.589930
6,FA 20:4;O3,1.464583,1.901950,2.214350,6.653617,2.092117,3.030550,1.680467,1.000000,1.241933,...,0.825845,1.378721,0.742650,0.832812,0.586108,0.190338,0.226654,1.798856,0.492296,0.879896
7,FA 20:3;O4,12.630633,22.740717,4.318200,57.447400,16.070783,16.813233,14.514317,13.899650,8.437883,...,0.707590,13.831865,4.194488,4.051846,0.097413,0.354509,0.110990,4.954269,1.621392,5.281118
8,FA 20:5;O,1.000000,1.114383,1.000000,1.262167,1.235583,1.143267,2.361417,1.300450,1.000000,...,1.160751,1.177828,1.021903,1.021903,0.251531,0.241767,0.258289,0.988394,0.864752,1.045589
9,FA 22:6;O,61.110000,224.869817,29.000933,163.637600,123.104650,144.193700,552.660667,215.540283,432.072117,...,1.583026,2.700509,0.643392,0.326899,1.131035,3.943225,0.805454,1.419525,2.145855,1.436300

In [51]:
family_col = [
    col for col in species.columns if "feature" in col]
family_col

['feature']

In [52]:
ratio_cols_D0 = [
    col for col in species.columns if "D0_D60" in col]
ratio_cols_D3 = [
    col for col in species.columns if "D3_D60" in col]
ratio_cols_D10 = [
    col for col in species.columns if "D10_D60" in col]

In [53]:
ratio_data_D0 = species[family_col + ratio_cols_D0]
ratio_data_D3 = species[family_col + ratio_cols_D3]
ratio_data_D10 = species[family_col + ratio_cols_D10]

In [54]:
ordered_columns = [
    "feature",
    "KT-539_D0_D60", "BS-671_D0_D60", "KT-805_D0_D60", "BS-336_D0_D60",
    "BS-082_D0_D60", "BS-351_D0_D60", "BS-377_D0_D60", "KT-313_D0_D60",
    "BS-364_D0_D60", "KT-880_D0_D60", "JV-138_D0_D60", "KT-412_D0_D60",
    "KT-771_D0_D60", "KT-723_D0_D60", "KT-538_D0_D60", "KT-716_D0_D60",
    "KT-974_D0_D60", "KT-537_D0_D60", "KT-445_D0_D60", "BS-346_D0_D60",
    "KT-663_D0_D60", "KT-695_D0_D60", "BS-064_D0_D60", "KT-705_D0_D60",
    "KT-347_D0_D60", "KT-515_D0_D60", "KT-718_D0_D60", "KT-417_D0_D60",
    "KT-522_D0_D60", "KT-312_D0_D60", "JV-157_D0_D60", "KT-193_D0_D60",
    "JV-035_D0_D60", "KT-434_D0_D60", "KT-247_D0_D60", "KT-612_D0_D60",
    "KT-525_D0_D60", "KT-352_D0_D60", "JV-148_D0_D60"
]

ratio_data_D0 = ratio_data_D0[ordered_columns]

In [55]:
ordered_columns = [
    "feature",
    "KT-539_D3_D60", "BS-671_D3_D60", "KT-805_D3_D60", "BS-336_D3_D60",
    "BS-082_D3_D60", "BS-351_D3_D60", "BS-377_D3_D60", "KT-313_D3_D60",
    "BS-364_D3_D60", "KT-880_D3_D60", "JV-138_D3_D60", "KT-412_D3_D60",
    "KT-771_D3_D60", "KT-723_D3_D60", "KT-538_D3_D60", "KT-716_D3_D60",
    "KT-974_D3_D60", "KT-537_D3_D60", "KT-445_D3_D60", "BS-346_D3_D60",
    "KT-663_D3_D60", "KT-695_D3_D60", "BS-064_D3_D60", "KT-705_D3_D60",
    "KT-347_D3_D60", "KT-515_D3_D60", "KT-718_D3_D60", "KT-417_D3_D60",
    "KT-522_D3_D60", "KT-312_D3_D60", "JV-157_D3_D60", "KT-193_D3_D60",
    "JV-035_D3_D60", "KT-434_D3_D60", "KT-247_D3_D60", "KT-612_D3_D60",
    "KT-525_D3_D60", "KT-352_D3_D60", "JV-148_D3_D60"
]

ratio_data_D3 = ratio_data_D3[ordered_columns]

In [56]:
ordered_columns = [
    "feature",
    "KT-539_D10_D60", "BS-671_D10_D60", "KT-805_D10_D60", "BS-336_D10_D60",
    "BS-082_D10_D60", "BS-351_D10_D60", "BS-377_D10_D60", "KT-313_D10_D60",
    "BS-364_D10_D60", "KT-880_D10_D60", "JV-138_D10_D60", "KT-412_D10_D60",
    "KT-771_D10_D60", "KT-723_D10_D60", "KT-538_D10_D60", "KT-716_D10_D60",
    "KT-974_D10_D60", "KT-537_D10_D60", "KT-445_D10_D60", "BS-346_D10_D60",
    "KT-663_D10_D60", "KT-695_D10_D60", "BS-064_D10_D60", "KT-705_D10_D60",
    "KT-347_D10_D60", "KT-515_D10_D60", "KT-718_D10_D60", "KT-417_D10_D60",
    "KT-522_D10_D60", "KT-312_D10_D60", "JV-157_D10_D60", "KT-193_D10_D60",
    "JV-035_D10_D60", "KT-434_D10_D60", "KT-247_D10_D60", "KT-612_D10_D60",
    "KT-525_D10_D60", "KT-352_D10_D60", "JV-148_D10_D60"
]

ratio_data_D10 = ratio_data_D10[ordered_columns]

In [57]:
# Sauvegarder le nouveau fichier
outfileD0 = "/Users/loictalignani/research/project/lipidomics/data/lipidsig_datasets/Oxylipines/Ratio_lipid_abundance_oxylipins_Div1_D0.tsv"
ratio_data_D0.to_csv(outfileD0, sep="\t", index=False)

print(f"Fichier enregistré : {outfileD0}")

# Sauvegarder le nouveau fichier
outfileD03 = "/Users/loictalignani/research/project/lipidomics/data/lipidsig_datasets/Oxylipines/Ratio_lipid_abundance_oxylipins_Div1_D03.tsv"
ratio_data_D3.to_csv(outfileD03, sep="\t", index=False)

print(f"Fichier enregistré : {outfileD03}")

# Sauvegarder le nouveau fichier
outfileD10 = "/Users/loictalignani/research/project/lipidomics/data/lipidsig_datasets/Oxylipines/Ratio_lipid_abundance_oxylipins_Div1_D10.tsv"
ratio_data_D10.to_csv(outfileD10, sep="\t", index=False)

print(f"Fichier enregistré : {outfileD10}")

Fichier enregistré : /Users/loictalignani/research/project/lipidomics/data/lipidsig_datasets/Oxylipines/Ratio_lipid_abundance_oxylipins_Div1_D0.tsv
Fichier enregistré : /Users/loictalignani/research/project/lipidomics/data/lipidsig_datasets/Oxylipines/Ratio_lipid_abundance_oxylipins_Div1_D03.tsv
Fichier enregistré : /Users/loictalignani/research/project/lipidomics/data/lipidsig_datasets/Oxylipines/Ratio_lipid_abundance_oxylipins_Div1_D10.tsv