# Oxylipin pretreatment
Normalize dataset by division /D60 values

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Charger le fichier Excel
file_path = "/Users/loictalignani/research/project/lipidomics/data/raw_data/oxylipines.xlsx"
xls = pd.ExcelFile(file_path)

# Charger les données des onglets
species = pd.read_excel(xls, sheet_name="data")
patient_data = pd.read_excel(xls, sheet_name="order")

In [3]:
species

,feature,KT-312D10,BS-364D0,KT-412D60,KT-974D03,JV-138D0,BS-671D03,KT-723D10,KT-705D60,KT-434D03,...,KT-537D0,KT-313D03,JV-035D10,BS-377D03,KT-880D60,KT-434D0,JV-035D03,KT-412D0,BS-671D10,KT-974D60
0,9-HODE,14.865283,21.497567,10.846900,89.558500,35.857650,27.483217,14.128983,7.418400,28.676300,...,22.163550,10.877283,23.700650,39.977683,30.411150,13.210950,20.561650,13.653850,13.947750,17.897417
1,13-HODE,27.323333,47.252867,13.739850,108.001150,46.803067,33.524733,47.747450,19.417933,87.156267,...,33.607200,20.156767,47.817767,39.353600,63.388833,67.179217,82.700817,66.622750,89.898633,29.086750
2,"9,10-DiHOME",1.970350,2.820100,4.621233,13.864950,2.510167,0.598733,2.749933,1.201033,2.399867,...,5.272700,1.531750,3.214550,0.706083,4.146717,11.880800,4.403850,7.940333,7.006133,1.669117
3,"12,13-DiHOME",2.482433,2.256850,4.976750,19.789067,2.185733,0.613150,3.633650,0.937550,2.547783,...,9.651200,1.415483,3.704800,0.773417,4.887717,14.942933,4.206400,3.897400,6.528050,2.863050
4,9-OxoODE,1.736617,0.718367,0.000000,6.359050,0.563050,0.182233,0.134317,0.136050,0.545383,...,0.309400,0.456867,0.318400,0.863067,0.718200,0.000000,0.765183,0.825683,0.135683,0.185667
5,13-OxoODE,2.087400,0.942467,0.000000,7.480950,2.314950,0.626550,0.000000,0.234333,0.696083,...,0.000000,0.000000,1.037783,5.671217,1.413917,0.245317,0.687183,1.131417,0.437083,0.000000
6,"9,10,13-trihydroxy-11-octadecenoic acid",0.365767,0.308683,0.470983,5.466883,0.000000,0.198700,0.146267,0.245300,0.929750,...,1.623800,0.653533,0.445483,0.000000,0.856550,2.213133,0.252400,0.224117,0.355400,0.000000
7,"9S,12S,13S-trihydroxy-10E-octadecenoic acid",1.444417,1.234267,2.728650,15.297733,0.488017,0.925133,1.894683,1.061883,2.826267,...,7.591317,2.235617,1.810333,0.399067,3.932633,7.085850,1.777633,1.343283,5.634533,1.680733
8,"8,9-EET",0.762267,2.258633,0.000000,2.601133,0.828633,1.540600,2.979100,1.694300,2.106700,...,2.183283,0.411917,0.421850,1.616133,4.455650,10.225200,0.441017,1.487100,0.422867,0.000000
9,5-HETE,96.875467,118.989883,125.045100,156.136400,173.930333,193.978650,93.744783,49.465500,45.070200,...,204.277067,41.275050,87.794900,250.758000,50.098317,34.865733,5.566117,11.948700,97.012750,28.531367
10,8-HETE,5.122750,11.544283,3.944050,11.911617,7.966083,12.411300,13.142167,7.884467,6.457117,...,12.643333,3.576067,5.924617,13.396283,13.592617,16.789117,5.409967,4.487300,2.654633,2.134983
11,12-HETE,208.296150,954.274850,138.656383,927.740483,399.929917,444.516150,1101.600400,594.956517,569.948917,...,602.135917,239.159950,476.534667,396.728400,1245.418967,1847.866767,694.189617,497.236767,214.045200,216.583517
12,15-HETE,2.625817,7.134700,1.625100,7.220200,4.513850,6.996150,8.931017,5.307800,3.879550,...,6.514933,1.895517,3.454400,4.886667,9.232583,9.815700,6.056533,5.130683,5.986633,3.471233
13,5-OxoETE,3.551567,1.879733,1.222883,7.482233,2.134117,1.470550,0.862850,0.690883,0.357567,...,1.613083,0.573533,1.269017,9.375067,2.092650,0.362000,0.216750,0.373617,1.511600,0.186950
14,FA 20:4;O3,0.464583,0.901950,1.214350,5.653617,1.092117,2.030550,0.680467,0.000000,0.241933,...,2.012467,0.158750,0.787333,2.286550,0.741083,0.284450,0.000000,0.000000,0.854800,0.122467
15,FA 20:5;O2,0.000000,0.175033,0.000000,1.016367,0.110283,0.264150,0.202700,0.182933,0.000000,...,0.616167,0.095017,0.000000,0.185733,0.542500,0.000000,0.000000,0.000000,0.000000,0.074067
16,PGE2,0.000000,0.000000,0.000000,1.803233,0.496617,0.532217,0.549883,0.572317,0.000000,...,1.278900,0.427400,0.362933,0.843983,1.292833,0.000000,0.000000,0.000000,0.000000,0.343433
17,PGF2alpha,0.811083,3.146517,0.000000,11.769667,1.953550,2.005483,5.876433,6.946700,1.720017,...,7.814600,1.720133,1.969400,2.108350,10.375333,2.320033,1.870800,1.332200,0.000000,2.481367
18,TXB2,11.630633,21.740717,3.318200,56.447400,15.070783,15.813233,13.514317,12.899650,7.437883,...,35.334533,16.159983,21.632583,14.141217,28.506433,95.715767,5.948583,8.394733,5.458133,9.663317
19,9-HOTrE,0.285817,0.209100,0.239600,2.003167,0.407567,0.230850,0.108433,0.078517,0.439800,...,0.229983,0.389717,0.476833,0.505383,0.128317,0.070917,0.176700,0.897300,0.342217,0.786300
20,13-HOTrE,0.790617,0.853917,0.400450,2.109600,1.389600,0.567600,1.316717,0.561367,4.595717,...,0.727500,0.753217,1.760067,0.907933,1.164583,0.620700,2.756367,4.928133,2.141650,0.825833
21,18-HEPE,0.000000,0.114383,0.000000,0.262167,0.235583,0.143267,1.361417,0.300450,0.000000,...,0.108033,0.000000,0.192233,0.275617,-0.008483,0.072700,-0.013967,0.005250,0.000000,0.000000
22,14-HDoHE,60.110000,223.869817,28.000933,162.637600,122.104650,143.193700,551.660667,214.540283,431.072117,...,173.838250,69.858133,189.062833,153.918700,300.142383,199.861250,282.957033,218.716583,83.043167,78.768317
23,17-HDoHE,2.576700,4.189483,0.940117,2.810600,3.837083,4.924800,7.758467,4.075017,5.361400,...,5.879500,1.848200,3.341367,6.581000,5.781800,4.750100,7.603517,7.126567,3.898567,1.970417

In [4]:
species.dtypes

feature       object
KT-312D10    float64
BS-364D0     float64
KT-412D60    float64
KT-974D03    float64
              ...
KT-434D0     float64
JV-035D03    float64
KT-412D0     float64
BS-671D10    float64
KT-974D60    float64
Length: 160, dtype: object

In [5]:
# Extraire les noms de colonnes correspondant aux échantillons
sample_columns = [
    col for col in species.columns if "D0" in col or "D03" in col or "D10" in col or "D60" in col]

In [6]:
# Identifier les patients en récupérant les préfixes des colonnes
patients = set(col.split('D')[0]
               for col in species.columns[1:])  # Exclure 'feature'
patients

{'BS-064',
 'BS-082',
 'BS-336',
 'BS-346',
 'BS-351',
 'BS-364',
 'BS-377',
 'BS-671',
 'JV-035',
 'JV-138',
 'JV-148',
 'JV-157',
 'KT-193',
 'KT-247',
 'KT-312',
 'KT-313',
 'KT-347',
 'KT-352',
 'KT-412',
 'KT-417',
 'KT-434',
 'KT-445',
 'KT-515',
 'KT-522',
 'KT-525',
 'KT-537',
 'KT-538',
 'KT-539',
 'KT-612',
 'KT-663',
 'KT-695',
 'KT-705',
 'KT-716',
 'KT-718',
 'KT-723',
 'KT-771',
 'KT-805',
 'KT-880',
 'KT-926',
 'KT-927',
 'KT-928',
 'KT-974'}

In [7]:
offset = 1  # Offset à ajouter pour éviter la division par zéro

In [8]:
# Appliquer l'offset à toutes les colonnes de patients
for patient in patients:
    patient_cols = [col for col in species.columns if col.startswith(patient)]
    # Ajout de l'offset pour toutes les colonnes du patient
    species[patient_cols] += offset

In [9]:
# Calculer les ratios et créer les nouvelles colonnes
for patient in patients:
    d0_col, d3_col, d10_col, d60_col = f"{patient}D0", f"{patient}D03", f"{patient}D10", f"{patient}D60"

    if d60_col in species.columns:
        species[f"{patient}_D0_D60"] = species[d0_col] / species[d60_col]
        species[f"{patient}_D3_D60"] = species[d3_col] / species[d60_col]
        species[f"{patient}_D10_D60"] = species[d10_col] / species[d60_col]

/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D0_D60"] = species[d0_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D3_D60"] = species[d3_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D10_D60"] = species[d10_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D0_D60"] = species[d0_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D3_D60"] = species[d3_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D10_D60"] = species[d10_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D0_D60"] = species[d0_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D3_D60"] = species[d3_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D10_D60"] = species[d10_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D0_D60"] = species[d0_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D3_D60"] = species[d3_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D10_D60"] = species[d10_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D0_D60"] = species[d0_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D3_D60"] = species[d3_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D10_D60"] = species[d10_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D0_D60"] = species[d0_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D3_D60"] = species[d3_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D10_D60"] = species[d10_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D0_D60"] = species[d0_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D3_D60"] = species[d3_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D10_D60"] = species[d10_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D0_D60"] = species[d0_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D3_D60"] = species[d3_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D10_D60"] = species[d10_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D0_D60"] = species[d0_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D3_D60"] = species[d3_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D10_D60"] = species[d10_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D0_D60"] = species[d0_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D3_D60"] = species[d3_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D10_D60"] = species[d10_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D0_D60"] = species[d0_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D3_D60"] = species[d3_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D10_D60"] = species[d10_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D0_D60"] = species[d0_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D3_D60"] = species[d3_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D10_D60"] = species[d10_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D0_D60"] = species[d0_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D3_D60"] = species[d3_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D10_D60"] = species[d10_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D0_D60"] = species[d0_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D3_D60"] = species[d3_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D10_D60"] = species[d10_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D0_D60"] = species[d0_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D3_D60"] = species[d3_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D10_D60"] = species[d10_col] / species[d60_col]
/var/folders/d3/l5snwfsj7yb7zrln2fvzwpqr0000gn/T/ipykernel_75006/1705873891.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  species[f"{patient}_D0_D60"] = species[d0_col] / species[d60_col]

In [10]:
species

,feature,KT-312D10,BS-364D0,KT-412D60,KT-974D03,JV-138D0,BS-671D03,KT-723D10,KT-705D60,KT-434D03,...,KT-723_D10_D60,BS-082_D0_D60,BS-082_D3_D60,BS-082_D10_D60,JV-138_D0_D60,JV-138_D3_D60,JV-138_D10_D60,BS-364_D0_D60,BS-364_D3_D60,BS-364_D10_D60
0,9-HODE,15.865283,22.497567,11.846900,90.558500,36.857650,28.483217,15.128983,8.418400,29.676300,...,0.632885,12.144158,20.901049,1.121032,0.312892,0.142642,0.237797,0.113751,0.355322,0.196746
1,13-HODE,28.323333,48.252867,14.739850,109.001150,47.803067,34.524733,48.747450,20.417933,88.156267,...,1.163771,13.251886,21.811315,4.018942,0.306218,0.194506,0.333465,0.190865,0.241290,0.220880
2,"9,10-DiHOME",2.970350,3.820100,5.621233,14.864950,3.510167,1.598733,3.749933,2.201033,3.399867,...,1.152702,0.767151,0.711355,7.939127,0.930055,2.618850,0.975774,0.442874,1.466490,0.260309
3,"12,13-DiHOME",3.482433,3.256850,5.976750,20.789067,3.185733,1.613150,4.633650,1.937550,3.547783,...,1.533170,0.349541,0.325722,3.176758,0.874305,1.885507,0.810940,0.521077,4.476540,0.270059
4,9-OxoODE,2.736617,1.718367,1.000000,7.359050,1.563050,1.182233,1.134317,1.136050,1.545383,...,1.004961,1.899190,2.671447,1.587983,0.968663,0.861233,0.986604,1.204181,2.234139,0.752371
5,13-OxoODE,3.087400,1.942467,1.000000,8.480950,3.314950,1.626550,1.000000,1.234333,1.696083,...,1.000000,7.438405,6.921456,1.803543,3.314950,1.421633,2.054017,0.450507,0.478230,0.337401
6,"9,10,13-trihydroxy-11-octadecenoic acid",1.365767,1.308683,1.470983,6.466883,1.000000,1.198700,1.146267,1.245300,1.929750,...,0.925715,0.983177,2.163615,4.668123,0.745221,1.044465,1.014631,0.833317,0.822715,0.740605
7,"9S,12S,13S-trihydroxy-10E-octadecenoic acid",2.444417,2.234267,3.728650,16.297733,1.488017,1.925133,2.894683,2.061883,3.826267,...,1.274536,0.545924,1.278083,5.427426,0.671953,1.189248,1.224132,0.719104,1.416847,0.669528
8,"8,9-EET",1.762267,3.258633,1.000000,3.601133,1.828633,2.540600,3.979100,2.694300,3.106700,...,1.323396,0.652186,0.929987,0.525833,1.828633,1.418333,2.751383,1.353084,0.758004,0.663289
9,5-HETE,97.875467,119.989883,126.045100,157.136400,174.930333,194.978650,94.744783,50.465500,46.070200,...,0.560043,12.018189,15.827305,1.522597,0.685547,0.431333,0.526913,0.151542,0.027557,0.333347
10,8-HETE,6.122750,12.544283,4.944050,12.911617,8.966083,13.411300,14.142167,8.884467,7.457117,...,1.234689,7.812527,14.794003,0.727537,0.441159,0.265213,0.509230,0.264948,0.084583,0.345287
11,12-HETE,209.296150,955.274850,139.656383,928.740483,400.929917,445.516150,1102.600400,595.956517,570.948917,...,2.506108,0.891546,1.060839,0.404069,1.698392,1.074706,2.516329,3.614035,1.218418,2.102489
12,15-HETE,3.625817,8.134700,2.625100,8.220200,5.513850,7.996150,9.931017,6.307800,4.879550,...,1.265294,11.792817,20.607883,1.013256,0.457808,0.347240,0.869538,0.335491,0.124681,0.334214
13,5-OxoETE,4.551567,2.879733,2.222883,8.482233,3.134117,2.470550,1.862850,1.690883,1.357567,...,1.017682,8.248146,10.525630,1.508756,1.970998,1.719035,2.259855,0.775258,0.320528,0.516218
14,FA 20:4;O3,1.464583,1.901950,2.214350,6.653617,2.092117,3.030550,1.680467,1.000000,1.241933,...,0.646292,6.397845,7.126358,1.116003,0.938295,0.897139,1.000553,0.201841,0.106123,0.256869
15,FA 20:5;O2,1.000000,1.175033,1.000000,2.016367,1.110283,1.264150,1.202700,1.182933,1.000000,...,1.202700,2.977817,4.618067,1.254950,1.110283,1.118283,1.401833,0.777550,0.661726,0.661726
16,PGE2,1.000000,1.000000,1.000000,2.803233,1.496617,1.532217,1.549883,1.572317,1.000000,...,1.075959,2.585185,3.653693,0.455657,1.496617,1.000000,1.887967,0.314065,0.314065,0.314065
17,PGF2alpha,1.811083,4.146517,1.000000,12.769667,2.953550,3.005483,6.876433,7.946700,2.720017,...,6.876433,1.130086,0.924251,0.230769,2.953550,3.659017,8.171017,4.146517,3.307600,1.000000
18,TXB2,12.630633,22.740717,4.318200,57.447400,16.070783,16.813233,14.514317,13.899650,8.437883,...,3.403894,0.755866,0.782214,0.190562,13.351338,8.074147,19.668684,2.133869,1.657547,0.927212
19,9-HOTrE,1.285817,1.209100,1.239600,3.003167,1.407567,1.230850,1.108433,1.078517,1.439800,...,0.891728,9.615155,5.335127,1.222191,0.637860,0.611418,0.665103,0.300401,1.280140,0.327155
20,13-HOTrE,1.790617,1.853917,1.400450,3.109600,2.389600,1.567600,2.316717,1.561367,5.595717,...,1.025936,17.410822,7.921159,1.461492,0.712201,0.553295,0.725628,0.293346,0.483072,0.328141
21,18-HEPE,1.000000,1.114383,1.000000,1.262167,1.235583,1.143267,2.361417,1.300450,1.000000,...,1.992476,11.469650,12.661033,1.097500,1.054012,0.853048,0.870948,0.291157,0.261272,0.276439
22,14-HDoHE,61.110000,224.869817,29.000933,163.637600,123.104650,144.193700,552.660667,215.540283,432.072117,...,2.232790,3.335631,3.643886,1.857773,0.889123,0.293957,0.791245,1.545090,0.448019,1.088488
23,17-HDoHE,3.576700,5.189483,1.940117,3.810600,4.837083,5.924800,8.758467,5.075017,6.361400,...,1.153776,32.330919,33.512287,1.948160,0.398973,0.230862,0.383764,0.169667,0.083852,0.235561

In [13]:
family_col = [
    col for col in species.columns if "feature" in col]
family_col

['feature']

In [16]:
ratio_cols_D0 = [
    col for col in species.columns if "D0_D60" in col]
ratio_cols_D3 = [
    col for col in species.columns if "D3_D60" in col]
ratio_cols_D10 = [
    col for col in species.columns if "D10_D60" in col]

In [17]:
ratio_data_D0 = species[family_col + ratio_cols_D0]
ratio_data_D3 = species[family_col + ratio_cols_D3]
ratio_data_D10 = species[family_col + ratio_cols_D10]

In [24]:
ordered_columns = [
    "feature",
    "KT-539_D0_D60", "BS-671_D0_D60", "KT-805_D0_D60", "BS-336_D0_D60",
    "BS-082_D0_D60", "BS-351_D0_D60", "BS-377_D0_D60", "KT-313_D0_D60",
    "BS-364_D0_D60", "KT-880_D0_D60", "JV-138_D0_D60", "KT-412_D0_D60",
    "KT-771_D0_D60", "KT-723_D0_D60", "KT-538_D0_D60", "KT-716_D0_D60",
    "KT-974_D0_D60", "KT-537_D0_D60", "KT-445_D0_D60", "BS-346_D0_D60",
    "KT-663_D0_D60", "KT-695_D0_D60", "BS-064_D0_D60", "KT-705_D0_D60",
    "KT-347_D0_D60", "KT-515_D0_D60", "KT-718_D0_D60", "KT-417_D0_D60",
    "KT-522_D0_D60", "KT-312_D0_D60", "JV-157_D0_D60", "KT-193_D0_D60",
    "JV-035_D0_D60", "KT-434_D0_D60", "KT-247_D0_D60", "KT-612_D0_D60",
    "KT-525_D0_D60", "KT-352_D0_D60", "JV-148_D0_D60"
]

ratio_data_D0 = ratio_data_D0[ordered_columns]

In [25]:
ordered_columns = [
    "feature",
    "KT-539_D3_D60", "BS-671_D3_D60", "KT-805_D3_D60", "BS-336_D3_D60",
    "BS-082_D3_D60", "BS-351_D3_D60", "BS-377_D3_D60", "KT-313_D3_D60",
    "BS-364_D3_D60", "KT-880_D3_D60", "JV-138_D3_D60", "KT-412_D3_D60",
    "KT-771_D3_D60", "KT-723_D3_D60", "KT-538_D3_D60", "KT-716_D3_D60",
    "KT-974_D3_D60", "KT-537_D3_D60", "KT-445_D3_D60", "BS-346_D3_D60",
    "KT-663_D3_D60", "KT-695_D3_D60", "BS-064_D3_D60", "KT-705_D3_D60",
    "KT-347_D3_D60", "KT-515_D3_D60", "KT-718_D3_D60", "KT-417_D3_D60",
    "KT-522_D3_D60", "KT-312_D3_D60", "JV-157_D3_D60", "KT-193_D3_D60",
    "JV-035_D3_D60", "KT-434_D3_D60", "KT-247_D3_D60", "KT-612_D3_D60",
    "KT-525_D3_D60", "KT-352_D3_D60", "JV-148_D3_D60"
]

ratio_data_D3 = ratio_data_D3[ordered_columns]

In [26]:
ordered_columns = [
    "feature",
    "KT-539_D10_D60", "BS-671_D10_D60", "KT-805_D10_D60", "BS-336_D10_D60",
    "BS-082_D10_D60", "BS-351_D10_D60", "BS-377_D10_D60", "KT-313_D10_D60",
    "BS-364_D10_D60", "KT-880_D10_D60", "JV-138_D10_D60", "KT-412_D10_D60",
    "KT-771_D10_D60", "KT-723_D10_D60", "KT-538_D10_D60", "KT-716_D10_D60",
    "KT-974_D10_D60", "KT-537_D10_D60", "KT-445_D10_D60", "BS-346_D10_D60",
    "KT-663_D10_D60", "KT-695_D10_D60", "BS-064_D10_D60", "KT-705_D10_D60",
    "KT-347_D10_D60", "KT-515_D10_D60", "KT-718_D10_D60", "KT-417_D10_D60",
    "KT-522_D10_D60", "KT-312_D10_D60", "JV-157_D10_D60", "KT-193_D10_D60",
    "JV-035_D10_D60", "KT-434_D10_D60", "KT-247_D10_D60", "KT-612_D10_D60",
    "KT-525_D10_D60", "KT-352_D10_D60", "JV-148_D10_D60"
]

ratio_data_D10 = ratio_data_D10[ordered_columns]

In [28]:
# Sauvegarder le nouveau fichier
outfileD0 = "/Users/loictalignani/research/project/lipidomics/data/lipidsig_datasets/Oxylipines/Ratio_lipid_abundance_oxylipins_D0.tsv"
ratio_data_D0.to_csv(outfileD0, sep="\t", index=False)

print(f"Fichier enregistré : {outfileD0}")

# Sauvegarder le nouveau fichier
outfileD03 = "/Users/loictalignani/research/project/lipidomics/data/lipidsig_datasets/Oxylipines/Ratio_lipid_abundance_oxylipins_D03.tsv"
ratio_data_D3.to_csv(outfileD03, sep="\t", index=False)

print(f"Fichier enregistré : {outfileD03}")

# Sauvegarder le nouveau fichier
outfileD10 = "/Users/loictalignani/research/project/lipidomics/data/lipidsig_datasets/Oxylipines/Ratio_lipid_abundance_oxylipins_D10.tsv"
ratio_data_D10.to_csv(outfileD10, sep="\t", index=False)

print(f"Fichier enregistré : {outfileD10}")

Fichier enregistré : /Users/loictalignani/research/project/lipidomics/data/lipidsig_datasets/Oxylipines/Ratio_lipid_abundance_oxylipins_D0.tsv
Fichier enregistré : /Users/loictalignani/research/project/lipidomics/data/lipidsig_datasets/Oxylipines/Ratio_lipid_abundance_oxylipins_D03.tsv
Fichier enregistré : /Users/loictalignani/research/project/lipidomics/data/lipidsig_datasets/Oxylipines/Ratio_lipid_abundance_oxylipins_D10.tsv